---
- hosts: 192.168.1.17
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
   
    - name: nginx start
      service:
        name: nginx
        state: started    


    - name: copy the domain file and restart nginx
      copy:
        src:   /home/ubuntu/domain
        dest: /etc/nginx/sites-enabled  
        remote_src: yes


    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes  




   Stop and uninstall


---
- hosts: 192.168.1.24
 become: true
 tasks:
   - name: stop nginx
     service:
         name: nginx
         state: stopped
   - name: uninstall nginx
     apt: name=nginx state=absent




